# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Arian Morteza
#title: Senior Network System Administrator
email: arimorteza@gmail.com
website: https://aarian.github.io/

# Social links
#twitter_username: facespics
github_username:  Aarian
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: arian-morteza
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 My name is Arian (Persian : آریان).  I received my master degree in Artificial Intelligence from Department of Computer Engineering , Amirkabir University of  Technology (Tehran Polytechnic). Now, I am a research assistant at SDA-LAB under the supervision of Dr. Amirmazlaghani. I also received my B.Sc in Computer Engineering (Computer Hardware) from CSE & IT Department of Shiraz University. 
I enjoy intuitively analyze and work on the theoretical aspects of the different existing applications of artificial intelligence! I like to work on the theoretical sides, and employ the methods on various types of data such as images, videos, texts, etc. I am broadly interested in the field of Statistical Machine Learning, Statistical Pattern Recognition, Graph Signal Processing, and Complex Network Analysis. 
Currently, my research topic focuses on the statistical modeling of space-time-frequency representations in image processing. More specifically, it aims to analyze an image to find an informative representation in a new domain, and statistically model the coefficients of the representation.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
